name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        target: [
          # aarch64-linux-gnu,
          # aarch64-linux-musl,
          x86_64-linux-gnu,
          x86_64-linux-musl,
          # aarch64-macos,
          # x86_64-macos,
          # x86_64-windows-gnu
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Nix and use that to run our tests so our environment matches exactly.
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Run our checks to catch quick issues
      - run: nix flake check

      - run: nix develop -c zig env

      - name: Run zig fmt
        if: matrix.os == 'ubuntu-latest'
        run: nix develop -c zig fmt --check .

      - name: Run tests with coverage
        run: nix develop -c zig build --summary all -Dcoverage -Dtarget=${{ matrix.target }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: zig-out/coverage/kcov-merged
          fail_ci_if_error: true
          verbose: true

